### ISSUE TITLE
Invalid subscription packet being sent

### ISSUE THREAD

**Issue by pitabwire** [jeffallen/mqtt#7]
I am experiencing invalid subscription error messages while load testing this [mqtt v3.1/v3.1.1 broker] (https://github.com/caricah/iotracah). Could you point/assist me get the tests working. Mainly I would like to get its limits on a single 8GB server.

**Comment by jeffallen** [comment]
Sorry, it is not very convenient for me to run the server in question (java = yuck).  If you can add more details like a packet capture and a traceback from the java server I can take a look.

**Comment by pitabwire** [comment]
@jeffallen sorry it took so long to respond but finally I have most of what your requested. From the packet capture I realized you subscribe to the topic "loadtest/0". Of course I reduced the loadtest connection number to 2 for easier debuggability.
I am also sharing captures for mosquitto for comparisons sake.

1. JeffAllen Mqtt
-------------------------------------------------------------------------------------------------------
The packet capture screen-shot is ![fromjeffallen](https://cloud.githubusercontent.com/assets/4368681/11318110/26fc8016-9056-11e5-92c5-e8394c503797.png) 

On the broker side the packet is decoded using the netty mqtt codec and yields

 MqttMessage[fixedHeader=, variableHeader=, payload=]

2. Mosquitto 
----------------------------------------------------------------------------------------------------------------

Packet capture is : 
![frommosquitto](https://cloud.githubusercontent.com/assets/4368681/11318132/903d31ba-9056-11e5-92ad-1206631322ae.png)

On the broker side the decoded message or packet is 

MqttSubscribeMessage[fixedHeader=MqttFixedHeader[messageType=SUBSCRIBE, isDup=false, qosLevel=AT_LEAST_ONCE, isRetain=false, remainingLength=15], variableHeader=MqttMessageIdVariableHeader[messageId=1], payload=MqttSubscribePayload[MqttTopicSubscription[topicFilter=loadtest/0, qualityOfService=AT_MOST_ONCE]]]

I inspected the two payloads from the packet captures and realized a small difference in the bytes the 4th and last bytes are different.

**Comment by pitabwire** [comment]
@jeffallen I have tried a lot of things in my capacity to make sure the 4th byte goes to zero in vain. Could you spare sometime and aid us? If there is any extra information you would like let me know.

**Comment by jeffallen** [comment]
I'm a dad at home, and Christmas took priority over fun hacking. :) I'm looking at this this morning, and will get back to you. Thanks for the reminder.

**Comment by jeffallen** [comment]
Please try the fix, and if it works for you, close this issue.

Also: Can you add a page to the wiki talking about how you are using this?

**Comment by jeffallen** [comment]
The byte that differs is the low order 8 bits of the packet identifier:
https://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718025
"SUBSCRIBE, UNSUBSCRIBE, and PUBLISH (in cases where QoS > 0) Control Packets MUST contain a non-zero 16-bit Packet Identifier"

Loadtest is using a QoS of 1 (QosAtLeastOnce) so it should not be sending a packet id of 0, as it is doing.

You might want to file an issue on the Java mqtt decoder; it should have been doing something more useful than sending back an empty subscribe. It could have logged, or thrown an exception. The bug is mine, but they could have helped out a bit finding it. :)

**Comment by pitabwire** [comment]
Unfortunately the fix hasn't corrected the issue. I will document all the steps taken too. And thanks for your time @jeffallen

**Comment by jeffallen** [comment]
I suppose this is not practical to do, but could you try with netty 4? Because I noticed that you are currently using netty-codec, version: '5.0.0.Alpha2'.

Could you make your own version of MqttDecoder that overrides the netty one, letting you log the input and output of netty's MqttDecoder.decode() function? It really seems like it should be throwing an exception, which seems to be getting eaten by netty. If you can find out the exception, then we can work backwards in MqttDecoder.java and find out what I'm sending that is triggering it.

**Comment by pitabwire** [comment]
The fix actually works. It was a user problem compiling Go code. I didn't update the $GOROOT libraries before building.
